### ISSUE TITLE
Reduce displayed folder structure

### ISSUE THREAD

**Issue by Jorgemendozaesp** [simon-ball/PyEdna#3]
A suggestion to make the GUI easier to interact with:
The folder tree structure on the top-left includes an unnecessarily long branch of folders going back to the $HOME directory. It would be better in my opinion to only show the current directory and perhaps also the parent of it. This would make use of the empty space in the figure below to show the name of the files you are actually interested in =)
<img width="853" alt="issue1" src="https://user-images.githubusercontent.com/49160108/74936704-f2d94780-53ea-11ea-828f-36dcdc86b638.png">

**Comment by simon-ball** [comment]
I chose this layout based solely on the older Edna, and, to be sure, file-trees have gone somewhat out of stylesince the late 1980s. 

I shall rethink the best way to present this information. As a quick workaround, you can already open the default directory finder via Find Directory - allowing you to, e.g., paste in a file path from Windows Explorer.

**Comment by simon-ball** [comment]
Fixed in commit e733a1c: file tree removed as irrelevant. Directories can be located via Find Directory.
