### ISSUE TITLE
Fixed-slope SN-curve

### ISSUE THREAD

**Issue by Jorgemendozaesp** [simon-ball/PyEdna#5]
What is the function of the "Slope" box? It does not seem to have any effect. If the purpose is to fix the slope of the regression model, I would call it "Fix slope".
![Screenshot 2020-02-20 at 15 14 12](https://user-images.githubusercontent.com/49160108/74941654-ac3c1b00-53f3-11ea-91f4-a7d09fc3aa5e.png)

**Comment by simon-ball** [comment]
It is indeed intended to allow the user to force a particular slope. 

There was a bug in how this value was used in the linear regression, causing everything to fail if set to any value other than "None" (blank text box. That should now be fixed.
