### ISSUE TITLE
Plot limits

### ISSUE THREAD

**Issue by Jorgemendozaesp** [simon-ball/PyEdna#6]
The design curve is plotted within different x-axis limits than the mean curve:
![pyedna](https://user-images.githubusercontent.com/49160108/74944551-8401eb80-53f6-11ea-8eba-9420d077e88e.png)
 
It would be nice if the two lines plotted for the same xlim as the plot, i.e. N (min) and N (max).

**Comment by simon-ball** [comment]
Fixed, all curves are now based on the minimum and maximum X values of the data points.
