### ISSUE TITLE
Plot axis tick labels

### ISSUE THREAD

**Issue by Jorgemendozaesp** [simon-ball/PyEdna#7]
The axis tick labels are difficult to interpret. I understand the axis are log-log and the 1e1,1e2,1e3, etc. are marked as they should, while 2e1,3e1, etc. are labeled as 2,3, etc. For the x-axis this is no problem since the axis covers a long-enough range to understand the pattern, but for the y-axis this is confusing, see picture:
<img width="1134" alt="Screenshot 2020-02-24 at 10 36 00" src="https://user-images.githubusercontent.com/49160108/75141650-b6ab2d00-56f1-11ea-960e-65bb600e3aa8.png">

I did not understand why the axis would begin at 5 when the default is set to 50. This could be easily fixed by deleting the intermediate ticklabels (for the y-axis only?) and setting the default ylim(10,1000)

**Comment by simon-ball** [comment]
Fixed, Y axis is set either as request by the user, or it defaults to the range (10, 1000), which is large enough to make the log scaling clear. 
Minor tick axis labels removed on the Y axis
